import java.util.*;
import xinguan.platform.*;

final class AuditPages extends PageLayout {
  AuditPages(String version,AuthService.Session session){super(version,session);}
  String audit(List<AccessPlatform.AuditEntry> rows,Map<String,String> q,int offset){
    String category=q.getOrDefault("category","business");StringBuilder b=new StringBuilder(header()).append("<div class=\"page-shell\"><h1>操作记录</h1><p>业务记录仅限授权机构；私人草稿内容不公开。支行管理员的账号管理记录仅显示本人操作。日期按北京时间筛选。</p><form method=\"get\" action=\"/audit\" class=\"identity-card audit-filters\">"+hidden("submissionId",q.getOrDefault("submissionId",""))+"<label>记录类别<select name=\"category\">").append(option("business","业务修改",category));
    if(PlatformStore.isManager(currentSession.actor))b.append(option("security","账号与安全",category));
    b.append("</select></label><label>机构<select name=\"organization\">").append(option("","授权范围全部",q.get("organization")));
    if(AccessPolicy.all(currentSession.actor))b.append(option(Organizations.DIVISION,"分行",q.get("organization")));
    for(var org:Organizations.BRANCHES.entrySet())if(AccessPolicy.all(currentSession.actor)||org.getKey().equals(currentSession.actor.organizationId()))b.append(option(org.getKey(),org.getValue(),q.get("organization")));
    b.append("</select></label><label>表类型<select name=\"dataset\">").append(option("","全部",q.get("dataset")));for(var schema:DatasetSchema.all())b.append(option(schema.id,schema.label,q.get("dataset")));
    b.append("</select></label><label>开始日期<input name=\"from\" value=\"").append(e(q.get("from"))).append("\" placeholder=\"YYYY-MM-DD\"></label><label>结束日期<input name=\"through\" value=\"").append(e(q.get("through"))).append("\" placeholder=\"YYYY-MM-DD\"></label><label>操作人或编号<input name=\"search\" maxlength=\"100\" value=\"").append(e(q.get("search"))).append("\"></label><button class=\"btn btn-primary\" type=\"submit\">查询</button></form>");
    for(var row:rows){b.append("<section class=\"identity-card audit-item\"><h2>").append(e(row.actor())).append(" · ").append(e(action(row.action()))).append("</h2><p>").append(e(time(row.at()))).append(" · ").append(e(Organizations.label(row.organization()))).append(" · ").append(e(row.customer())).append("</p><p class=\"field-note access-break\">记录 ").append(e(row.recordId())).append(" · 请求 ").append(e(row.requestId()));if(!row.submissionId().isEmpty())b.append(" · 工作流单据 ").append(e(row.submissionId()));b.append("</p><p class=\"access-pre\">").append(e(row.details())).append("</p>");
      if(!row.before().isEmpty()||!row.after().isEmpty()){b.append("<div class=\"table-scroll\"><table class=\"data-table audit-diff\"><thead><tr><th>字段</th><th>修改前</th><th>修改后</th></tr></thead><tbody>");int size=Math.max(row.before().size(),row.after().size());for(int i=0;i<size;i++){String before=value(row.before(),i),after=value(row.after(),i);if(before.equals(after))continue;String title=!row.dataset().isEmpty()&&i<DatasetSchema.get(row.dataset()).width()?DatasetSchema.get(row.dataset()).fields.get(i).title():row.action().startsWith("USER_")&&i<5?List.of("统一认证号","姓名","角色","机构","启用状态").get(i):"字段 "+(i+1);b.append("<tr><td>").append(e(title)).append("</td><td class=\"diff-before access-pre\">").append(e(before)).append("</td><td class=\"diff-after access-pre\">").append(e(after)).append("</td></tr>");}b.append("</tbody></table></div>");}b.append("</section>");}
    if(rows.isEmpty())b.append("<div class=\"identity-card\">当前条件下没有操作记录</div>");StringBuilder url=new StringBuilder("/audit?category=").append(u(category));for(String key:List.of("organization","dataset","from","through","search","submissionId"))url.append('&').append(key).append('=').append(u(q.get(key)));
    return page("操作记录",b.append(AccessPages.pager(url.toString(),offset,rows.size())).append("</div>").toString());
  }
  private static String value(List<String> values,int index){return index<values.size()?values.get(index):"";}
  private static String action(String action){return switch(action){case "DIRECT_EDIT","DIRECT_SUBMIT"->"直接提交";case "REVIEW_DECISION"->"复核通过";case "REVIEW_RETURNED"->"复核退回";case "SUBMIT"->"提交复核";case "IMPORT_ADD"->"导入新增";case "IMPORT_UPDATE"->"导入更新";case "USER_CREATE"->"创建人员";case "USER_UPDATE"->"修改人员";case "USER_DISABLE"->"停用人员";case "USER_PASSWORD_RESET"->"重置密码";case "PASSWORD_CHANGE"->"本人改密";case "SECURITY_ACK"->"安全提示确认";case "ACCESS_APPROVE"->"权限申请批准";case "ACCESS_REJECT"->"权限申请退回";case "ACCESS_ESCALATE"->"权限申请转交";default->action;};}
}
