ALTER TABLE drafts ADD COLUMN IF NOT EXISTS prior_submission_id VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS mode VARCHAR(20) NOT NULL DEFAULT 'REVIEW';
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS owner_name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS reviewer_name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS draft_id VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS draft_revision BIGINT NOT NULL DEFAULT 0;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS prior_submission_id VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS preview_id VARCHAR(80);
CREATE UNIQUE INDEX IF NOT EXISTS idx_submission_preview ON submissions(preview_id);
CREATE INDEX IF NOT EXISTS idx_drafts_owner ON drafts(owner_id,organization_id,dataset,updated_at);
CREATE INDEX IF NOT EXISTS idx_submissions_scope ON submissions(organization_id,state,created_at);
CREATE TABLE IF NOT EXISTS workflow_previews (id VARCHAR(80) PRIMARY KEY, owner_id VARCHAR(80) NOT NULL, identity_revision BIGINT NOT NULL, organization_id VARCHAR(32) NOT NULL, dataset VARCHAR(32) NOT NULL, mode VARCHAR(20) NOT NULL, draft_id VARCHAR(80) NOT NULL, draft_revision BIGINT NOT NULL, prior_submission_id VARCHAR(80) NOT NULL, payload CLOB NOT NULL, created_at VARCHAR(40) NOT NULL, expires_at VARCHAR(40) NOT NULL, result_id VARCHAR(80));
CREATE INDEX IF NOT EXISTS idx_previews_owner ON workflow_previews(owner_id,created_at);
CREATE TABLE IF NOT EXISTS submission_items (submission_id VARCHAR(80) NOT NULL REFERENCES submissions(id), record_id VARCHAR(80) NOT NULL REFERENCES official_records(id), period_start DATE NOT NULL, period_end DATE NOT NULL, PRIMARY KEY(submission_id,record_id));
CREATE INDEX IF NOT EXISTS idx_submission_period ON submission_items(period_start,period_end);
CREATE TABLE IF NOT EXISTS pending_submission_records (owner_id VARCHAR(80) NOT NULL, record_id VARCHAR(80) NOT NULL REFERENCES official_records(id), submission_id VARCHAR(80) NOT NULL REFERENCES submissions(id), PRIMARY KEY(owner_id,record_id));
ALTER TABLE notification_events ADD COLUMN IF NOT EXISTS event_key VARCHAR(100);
CREATE UNIQUE INDEX IF NOT EXISTS idx_notice_event_key ON notification_events(event_key);
ALTER TABLE notification_receipts ADD COLUMN IF NOT EXISTS recipient_org VARCHAR(32) NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_notice_user ON notification_receipts(user_id,recipient_org,read_at);
CREATE TABLE IF NOT EXISTS workflow_audit_links (submission_id VARCHAR(80) NOT NULL REFERENCES submissions(id), event_id VARCHAR(80) NOT NULL REFERENCES audit_events(id), PRIMARY KEY(submission_id,event_id));
